services:
  rss_bot:
    image: rss-bot
    container_name: rss-bot
    build: .
    command: go run *.go
    env_file:
      - .environment
    volumes:
      - .:/code

networks:
  default:
    name: rss-bot
